---
version: "2.1"
services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hongkong
      # - PUBLIC_KEY_FILE=/secrets/id_rsa.pub #optional
      - PUBLIC_KEY_DIR=/secrets
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=false #optional
      # - USER_PASSWORD=password #optional
      # - USER_PASSWORD_FILE=/secrets/password.txt #optional
      - USER_NAME=linuxserver.io #optional
    volumes:
      - ./config:/config
      - ./secrets:/secrets
    ports:
      - 2222:2222
    restart: unless-stopped